<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Wilayah;
use App\Models\StandarBb;
use App\Models\Perkembangan;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Create admin user
        User::create([
            'name' => 'Administrator',
            'email' => 'admin@admin.com',
            'phone' => '0', // Added phone number
            'password' => bcrypt('admin123'),
            'email_verified_at' => now(),
            'is_admin' => true,
        ]);
        User::create([
            'name' => 'User',
            'email' => 'user@user.com',
            'phone' => '1', // Added phone number
            'password' => bcrypt('user123'),
            'email_verified_at' => now(),
            'is_admin' => false,
        ]);

        for ($i = 1; $i <= 10; $i++) {
            Wilayah::create([
                'name' => 'Wilayah ' . $i
            ]);
        }

        // Create age ranges for babies (0-60 months in increments of 3)
        for ($i = 0; $i <= 60; $i += 3) {
            \App\Models\UsiaBayi::create([
                'rentang' => $i
            ]);
        }

        // Create standar BBS data
        $standarBbsData = [
            ["id"=>"1","jenis_kelamin"=>"L","umur"=>"0","m3"=>"2.1","m2"=>"2.5","m1"=>"2.9","median"=>"3.3","p1"=>"3.9","p2"=>"4.4","p3"=>"5"],
            ["id"=>"2","jenis_kelamin"=>"L","umur"=>"1","m3"=>"2.9","m2"=>"3.4","m1"=>"3.9","median"=>"4.5","p1"=>"5.1","p2"=>"5.8","p3"=>"6.6"],
            ["id"=>"3","jenis_kelamin"=>"L","umur"=>"2","m3"=>"3.8","m2"=>"4.3","m1"=>"4.9","median"=>"5.6","p1"=>"6.3","p2"=>"7.1","p3"=>"8"],
            ["id"=>"4","jenis_kelamin"=>"L","umur"=>"3","m3"=>"4.4","m2"=>"5","m1"=>"5.7","median"=>"6.4","p1"=>"7.2","p2"=>"8","p3"=>"9"],
            ["id"=>"5","jenis_kelamin"=>"L","umur"=>"4","m3"=>"4.9","m2"=>"5.6","m1"=>"6.2","median"=>"7","p1"=>"7.8","p2"=>"8.7","p3"=>"9.7"],
            ["id"=>"6","jenis_kelamin"=>"L","umur"=>"5","m3"=>"5.3","m2"=>"6","m1"=>"6.7","median"=>"7.5","p1"=>"8.4","p2"=>"9.3","p3"=>"10.4"],
            ["id"=>"7","jenis_kelamin"=>"L","umur"=>"6","m3"=>"5.7","m2"=>"6.4","m1"=>"7.1","median"=>"7.9","p1"=>"8.8","p2"=>"9.8","p3"=>"10.9"],
            ["id"=>"8","jenis_kelamin"=>"L","umur"=>"7","m3"=>"5.9","m2"=>"6.7","m1"=>"7.4","median"=>"8.3","p1"=>"9.2","p2"=>"10.3","p3"=>"11.4"],
            ["id"=>"9","jenis_kelamin"=>"L","umur"=>"8","m3"=>"6.2","m2"=>"6.9","m1"=>"7.7","median"=>"8.6","p1"=>"9.6","p2"=>"10.7","p3"=>"11.9"],
            ["id"=>"10","jenis_kelamin"=>"L","umur"=>"9","m3"=>"6.4","m2"=>"7.1","m1"=>"8","median"=>"8.9","p1"=>"9.9","p2"=>"11","p3"=>"12.3"],
            ["id"=>"11","jenis_kelamin"=>"L","umur"=>"10","m3"=>"6.6","m2"=>"7.4","m1"=>"8.2","median"=>"9.2","p1"=>"10.2","p2"=>"11.4","p3"=>"12.7"],
            ["id"=>"12","jenis_kelamin"=>"L","umur"=>"11","m3"=>"6.8","m2"=>"7.6","m1"=>"8.4","median"=>"9.4","p1"=>"10.5","p2"=>"11.7","p3"=>"13"],
            ["id"=>"13","jenis_kelamin"=>"L","umur"=>"12","m3"=>"6.9","m2"=>"7.7","m1"=>"8.6","median"=>"9.6","p1"=>"10.8","p2"=>"12","p3"=>"13.3"],
            ["id"=>"14","jenis_kelamin"=>"L","umur"=>"13","m3"=>"7.1","m2"=>"7.9","m1"=>"8.8","median"=>"9.9","p1"=>"11","p2"=>"12.3","p3"=>"13.7"],
            ["id"=>"15","jenis_kelamin"=>"L","umur"=>"14","m3"=>"7.2","m2"=>"8.1","m1"=>"9","median"=>"10.1","p1"=>"11.3","p2"=>"12.6","p3"=>"14"],
            ["id"=>"16","jenis_kelamin"=>"L","umur"=>"15","m3"=>"7.4","m2"=>"8.3","m1"=>"9.2","median"=>"10.3","p1"=>"11.5","p2"=>"12.8","p3"=>"14.3"],
            ["id"=>"17","jenis_kelamin"=>"L","umur"=>"16","m3"=>"7.5","m2"=>"8.4","m1"=>"9.4","median"=>"10.5","p1"=>"11.7","p2"=>"13.1","p3"=>"14.6"],
            ["id"=>"18","jenis_kelamin"=>"L","umur"=>"17","m3"=>"7.7","m2"=>"8.6","m1"=>"9.6","median"=>"10.7","p1"=>"12","p2"=>"13.4","p3"=>"14.9"],
            ["id"=>"19","jenis_kelamin"=>"L","umur"=>"18","m3"=>"7.8","m2"=>"8.8","m1"=>"9.8","median"=>"10.9","p1"=>"12.2","p2"=>"13.7","p3"=>"15.3"],
            ["id"=>"20","jenis_kelamin"=>"L","umur"=>"19","m3"=>"8","m2"=>"8.9","m1"=>"10","median"=>"11.1","p1"=>"12.5","p2"=>"13.9","p3"=>"15.6"],
            ["id"=>"21","jenis_kelamin"=>"L","umur"=>"20","m3"=>"8.1","m2"=>"9.1","m1"=>"10.1","median"=>"11.3","p1"=>"12.7","p2"=>"14.2","p3"=>"15.9"],
            ["id"=>"22","jenis_kelamin"=>"L","umur"=>"21","m3"=>"8.2","m2"=>"9.2","m1"=>"10.3","median"=>"11.5","p1"=>"12.9","p2"=>"14.5","p3"=>"16.2"],
            ["id"=>"23","jenis_kelamin"=>"L","umur"=>"22","m3"=>"8.4","m2"=>"9.4","m1"=>"10.5","median"=>"11.8","p1"=>"13.2","p2"=>"14.7","p3"=>"16.5"],
            ["id"=>"24","jenis_kelamin"=>"L","umur"=>"23","m3"=>"8.5","m2"=>"9.5","m1"=>"10.7","median"=>"12","p1"=>"13.4","p2"=>"15","p3"=>"16.8"],
            ["id"=>"25","jenis_kelamin"=>"L","umur"=>"24","m3"=>"8.6","m2"=>"9.7","m1"=>"10.8","median"=>"12.2","p1"=>"13.6","p2"=>"15.3","p3"=>"17.1"],
            ["id"=>"26","jenis_kelamin"=>"L","umur"=>"25","m3"=>"8.8","m2"=>"9.8","m1"=>"11","median"=>"12.4","p1"=>"13.9","p2"=>"15.5","p3"=>"17.5"],
            ["id"=>"27","jenis_kelamin"=>"L","umur"=>"26","m3"=>"8.9","m2"=>"10","m1"=>"11.2","median"=>"12.5","p1"=>"14.1","p2"=>"15.8","p3"=>"17.8"],
            ["id"=>"28","jenis_kelamin"=>"L","umur"=>"27","m3"=>"9","m2"=>"10.1","m1"=>"11.3","median"=>"12.7","p1"=>"14.3","p2"=>"16.1","p3"=>"18.1"],
            ["id"=>"29","jenis_kelamin"=>"L","umur"=>"28","m3"=>"9.1","m2"=>"10.2","m1"=>"11.5","median"=>"12.9","p1"=>"14.5","p2"=>"16.3","p3"=>"18.4"],
            ["id"=>"30","jenis_kelamin"=>"L","umur"=>"29","m3"=>"9.2","m2"=>"10.4","m1"=>"11.7","median"=>"13.1","p1"=>"14.8","p2"=>"16.6","p3"=>"18.7"],
            ["id"=>"31","jenis_kelamin"=>"L","umur"=>"30","m3"=>"9.4","m2"=>"10.5","m1"=>"11.8","median"=>"13.3","p1"=>"15","p2"=>"16.9","p3"=>"19"],
            ["id"=>"32","jenis_kelamin"=>"L","umur"=>"31","m3"=>"9.5","m2"=>"10.7","m1"=>"12","median"=>"13.5","p1"=>"15.2","p2"=>"17.1","p3"=>"19.3"],
            ["id"=>"33","jenis_kelamin"=>"L","umur"=>"32","m3"=>"9.6","m2"=>"10.8","m1"=>"12.1","median"=>"13.7","p1"=>"15.4","p2"=>"17.4","p3"=>"19.6"],
            ["id"=>"34","jenis_kelamin"=>"L","umur"=>"33","m3"=>"9.7","m2"=>"10.9","m1"=>"12.3","median"=>"13.8","p1"=>"15.6","p2"=>"17.6","p3"=>"19.9"],
            ["id"=>"35","jenis_kelamin"=>"L","umur"=>"34","m3"=>"9.8","m2"=>"11","m1"=>"12.4","median"=>"14","p1"=>"15.8","p2"=>"17.8","p3"=>"20.2"],
            ["id"=>"36","jenis_kelamin"=>"L","umur"=>"35","m3"=>"9.9","m2"=>"11.2","m1"=>"12.6","median"=>"14.2","p1"=>"16","p2"=>"18.1","p3"=>"20.4"],
            ["id"=>"37","jenis_kelamin"=>"L","umur"=>"36","m3"=>"10","m2"=>"11.3","m1"=>"12.7","median"=>"14.3","p1"=>"16.2","p2"=>"18.3","p3"=>"20.7"],
            ["id"=>"38","jenis_kelamin"=>"L","umur"=>"37","m3"=>"10.1","m2"=>"11.4","m1"=>"12.9","median"=>"14.5","p1"=>"16.4","p2"=>"18.6","p3"=>"21"],
            ["id"=>"39","jenis_kelamin"=>"L","umur"=>"38","m3"=>"10.2","m2"=>"11.5","m1"=>"13","median"=>"14.7","p1"=>"16.6","p2"=>"18.8","p3"=>"21.3"],
            ["id"=>"40","jenis_kelamin"=>"L","umur"=>"39","m3"=>"10.3","m2"=>"11.6","m1"=>"13.1","median"=>"14.8","p1"=>"16.8","p2"=>"19","p3"=>"21.6"],
            ["id"=>"41","jenis_kelamin"=>"L","umur"=>"40","m3"=>"10.4","m2"=>"11.8","m1"=>"13.3","median"=>"15","p1"=>"17","p2"=>"19.3","p3"=>"21.9"],
            ["id"=>"42","jenis_kelamin"=>"L","umur"=>"41","m3"=>"10.5","m2"=>"11.9","m1"=>"13.4","median"=>"15.2","p1"=>"17.2","p2"=>"19.5","p3"=>"22.1"],
            ["id"=>"43","jenis_kelamin"=>"L","umur"=>"42","m3"=>"10.6","m2"=>"12","m1"=>"13.6","median"=>"15.3","p1"=>"17.4","p2"=>"19.7","p3"=>"22.4"],
            ["id"=>"44","jenis_kelamin"=>"L","umur"=>"43","m3"=>"10.7","m2"=>"12.1","m1"=>"13.7","median"=>"15.5","p1"=>"17.6","p2"=>"20","p3"=>"22.7"],
            ["id"=>"45","jenis_kelamin"=>"L","umur"=>"44","m3"=>"10.8","m2"=>"12.2","m1"=>"13.8","median"=>"15.7","p1"=>"17.8","p2"=>"20.2","p3"=>"23"],
            ["id"=>"46","jenis_kelamin"=>"L","umur"=>"45","m3"=>"10.9","m2"=>"12.4","m1"=>"14","median"=>"15.8","p1"=>"18","p2"=>"20.5","p3"=>"23.3"],
            ["id"=>"47","jenis_kelamin"=>"L","umur"=>"46","m3"=>"11","m2"=>"12.5","m1"=>"14.1","median"=>"16","p1"=>"18.2","p2"=>"20.7","p3"=>"23.6"],
            ["id"=>"48","jenis_kelamin"=>"L","umur"=>"47","m3"=>"11.1","m2"=>"12.6","m1"=>"14.3","median"=>"16.2","p1"=>"18.4","p2"=>"20.9","p3"=>"23.9"],
            ["id"=>"49","jenis_kelamin"=>"L","umur"=>"48","m3"=>"11.2","m2"=>"12.7","m1"=>"14.4","median"=>"16.3","p1"=>"18.6","p2"=>"21.2","p3"=>"24.2"],
            ["id"=>"50","jenis_kelamin"=>"L","umur"=>"49","m3"=>"11.3","m2"=>"12.8","m1"=>"14.5","median"=>"16.5","p1"=>"18.8","p2"=>"21.4","p3"=>"24.5"],
            ["id"=>"51","jenis_kelamin"=>"L","umur"=>"50","m3"=>"11.4","m2"=>"12.9","m1"=>"14.7","median"=>"16.7","p1"=>"19","p2"=>"21.7","p3"=>"24.8"],
            ["id"=>"52","jenis_kelamin"=>"L","umur"=>"51","m3"=>"11.5","m2"=>"13.1","m1"=>"14.8","median"=>"16.8","p1"=>"19.2","p2"=>"21.9","p3"=>"25.1"],
            ["id"=>"53","jenis_kelamin"=>"L","umur"=>"52","m3"=>"11.6","m2"=>"13.2","m1"=>"15","median"=>"17","p1"=>"19.4","p2"=>"22.2","p3"=>"25.4"],
            ["id"=>"54","jenis_kelamin"=>"L","umur"=>"53","m3"=>"11.7","m2"=>"13.3","m1"=>"15.1","median"=>"17.2","p1"=>"19.6","p2"=>"22.4","p3"=>"25.7"],
            ["id"=>"55","jenis_kelamin"=>"L","umur"=>"54","m3"=>"11.8","m2"=>"13.4","m1"=>"15.2","median"=>"17.3","p1"=>"19.8","p2"=>"22.7","p3"=>"26"],
            ["id"=>"56","jenis_kelamin"=>"L","umur"=>"55","m3"=>"11.9","m2"=>"13.5","m1"=>"15.4","median"=>"17.5","p1"=>"20","p2"=>"22.9","p3"=>"26.3"],
            ["id"=>"57","jenis_kelamin"=>"L","umur"=>"56","m3"=>"12","m2"=>"13.6","m1"=>"15.5","median"=>"17.7","p1"=>"20.2","p2"=>"23.2","p3"=>"26.6"],
            ["id"=>"58","jenis_kelamin"=>"L","umur"=>"57","m3"=>"12.1","m2"=>"13.7","m1"=>"15.6","median"=>"17.8","p1"=>"20.4","p2"=>"23.4","p3"=>"26.9"],
            ["id"=>"59","jenis_kelamin"=>"L","umur"=>"58","m3"=>"12.2","m2"=>"13.8","m1"=>"15.8","median"=>"18","p1"=>"20.6","p2"=>"23.7","p3"=>"27.2"],
            ["id"=>"60","jenis_kelamin"=>"L","umur"=>"59","m3"=>"12.3","m2"=>"14","m1"=>"15.9","median"=>"18.2","p1"=>"20.8","p2"=>"23.9","p3"=>"27.6"],
            ["id"=>"61","jenis_kelamin"=>"L","umur"=>"60","m3"=>"12.4","m2"=>"14.1","m1"=>"16","median"=>"18.3","p1"=>"21","p2"=>"24.2","p3"=>"27.9"],
            ["id"=>"62","jenis_kelamin"=>"P","umur"=>"0","m3"=>"2","m2"=>"2.4","m1"=>"2.8","median"=>"3.2","p1"=>"3.7","p2"=>"4.2","p3"=>"4.8"],
            ["id"=>"63","jenis_kelamin"=>"P","umur"=>"1","m3"=>"2.7","m2"=>"3.2","m1"=>"3.6","median"=>"4.2","p1"=>"4.8","p2"=>"5.5","p3"=>"6.2"],
            ["id"=>"64","jenis_kelamin"=>"P","umur"=>"2","m3"=>"3.4","m2"=>"3.9","m1"=>"4.5","median"=>"5.1","p1"=>"5.8","p2"=>"6.6","p3"=>"7.5"],
            ["id"=>"65","jenis_kelamin"=>"P","umur"=>"3","m3"=>"4","m2"=>"4.5","m1"=>"5.2","median"=>"5.8","p1"=>"6.6","p2"=>"7.5","p3"=>"8.5"],
            ["id"=>"66","jenis_kelamin"=>"P","umur"=>"4","m3"=>"4.4","m2"=>"5","m1"=>"5.7","median"=>"6.4","p1"=>"7.3","p2"=>"8.2","p3"=>"9.3"],
            ["id"=>"67","jenis_kelamin"=>"P","umur"=>"5","m3"=>"4.8","m2"=>"5.4","m1"=>"6.1","median"=>"6.9","p1"=>"7.8","p2"=>"8.8","p3"=>"10"],
            ["id"=>"68","jenis_kelamin"=>"P","umur"=>"6","m3"=>"5.1","m2"=>"5.7","m1"=>"6.5","median"=>"7.3","p1"=>"8.2","p2"=>"9.3","p3"=>"10.6"],
            ["id"=>"69","jenis_kelamin"=>"P","umur"=>"7","m3"=>"5.3","m2"=>"6","m1"=>"6.8","median"=>"7.6","p1"=>"8.6","p2"=>"9.8","p3"=>"11.1"],
            ["id"=>"70","jenis_kelamin"=>"P","umur"=>"8","m3"=>"5.6","m2"=>"6.3","m1"=>"7","median"=>"7.9","p1"=>"9","p2"=>"10.2","p3"=>"11.6"],
            ["id"=>"71","jenis_kelamin"=>"P","umur"=>"9","m3"=>"5.8","m2"=>"6.5","m1"=>"7.3","median"=>"8.2","p1"=>"9.3","p2"=>"10.5","p3"=>"12"],
            ["id"=>"72","jenis_kelamin"=>"P","umur"=>"10","m3"=>"5.9","m2"=>"6.7","m1"=>"7.5","median"=>"8.5","p1"=>"9.6","p2"=>"10.9","p3"=>"12.4"],
            ["id"=>"73","jenis_kelamin"=>"P","umur"=>"11","m3"=>"6.1","m2"=>"6.9","m1"=>"7.7","median"=>"8.7","p1"=>"9.9","p2"=>"11.2","p3"=>"12.8"],
            ["id"=>"74","jenis_kelamin"=>"P","umur"=>"12","m3"=>"6.3","m2"=>"7","m1"=>"7.9","median"=>"8.9","p1"=>"10.1","p2"=>"11.5","p3"=>"13.1"],
            ["id"=>"75","jenis_kelamin"=>"P","umur"=>"13","m3"=>"6.4","m2"=>"7.2","m1"=>"8.1","median"=>"9.2","p1"=>"10.4","p2"=>"11.8","p3"=>"13.5"],
            ["id"=>"76","jenis_kelamin"=>"P","umur"=>"14","m3"=>"6.6","m2"=>"7.4","m1"=>"8.3","median"=>"9.4","p1"=>"10.6","p2"=>"12.1","p3"=>"13.8"],
            ["id"=>"77","jenis_kelamin"=>"P","umur"=>"15","m3"=>"6.7","m2"=>"7.6","m1"=>"8.5","median"=>"9.6","p1"=>"10.9","p2"=>"12.4","p3"=>"14.1"],
            ["id"=>"78","jenis_kelamin"=>"P","umur"=>"16","m3"=>"6.9","m2"=>"7.7","m1"=>"8.7","median"=>"9.8","p1"=>"11.1","p2"=>"12.6","p3"=>"14.5"],
            ["id"=>"79","jenis_kelamin"=>"P","umur"=>"17","m3"=>"7","m2"=>"7.9","m1"=>"8.9","median"=>"10","p1"=>"11.4","p2"=>"12.9","p3"=>"14.8"],
            ["id"=>"80","jenis_kelamin"=>"P","umur"=>"18","m3"=>"7.2","m2"=>"8.1","m1"=>"9.1","median"=>"10.2","p1"=>"11.6","p2"=>"13.2","p3"=>"15.1"],
            ["id"=>"81","jenis_kelamin"=>"P","umur"=>"19","m3"=>"7.3","m2"=>"8.2","m1"=>"9.2","median"=>"10.4","p1"=>"11.8","p2"=>"13.5","p3"=>"15.4"],
            ["id"=>"82","jenis_kelamin"=>"P","umur"=>"20","m3"=>"7.5","m2"=>"8.4","m1"=>"9.4","median"=>"10.6","p1"=>"12.1","p2"=>"13.7","p3"=>"15.7"],
            ["id"=>"83","jenis_kelamin"=>"P","umur"=>"21","m3"=>"7.6","m2"=>"8.6","m1"=>"9.6","median"=>"10.9","p1"=>"12.3","p2"=>"14","p3"=>"16"],
            ["id"=>"84","jenis_kelamin"=>"P","umur"=>"22","m3"=>"7.8","m2"=>"8.7","m1"=>"9.8","median"=>"11.1","p1"=>"12.5","p2"=>"14.3","p3"=>"16.4"],
            ["id"=>"85","jenis_kelamin"=>"P","umur"=>"23","m3"=>"7.9","m2"=>"8.9","m1"=>"10","median"=>"11.3","p1"=>"12.8","p2"=>"14.6","p3"=>"16.7"],
            ["id"=>"86","jenis_kelamin"=>"P","umur"=>"24","m3"=>"8.1","m2"=>"9","m1"=>"10.2","median"=>"11.5","p1"=>"13","p2"=>"14.8","p3"=>"17"],
            ["id"=>"87","jenis_kelamin"=>"P","umur"=>"25","m3"=>"8.2","m2"=>"9.2","m1"=>"10.3","median"=>"11.7","p1"=>"13.3","p2"=>"15.1","p3"=>"17.3"],
            ["id"=>"88","jenis_kelamin"=>"P","umur"=>"26","m3"=>"8.4","m2"=>"9.4","m1"=>"10.5","median"=>"11.9","p1"=>"13.5","p2"=>"15.4","p3"=>"17.7"],
            ["id"=>"89","jenis_kelamin"=>"P","umur"=>"27","m3"=>"8.5","m2"=>"9.5","m1"=>"10.7","median"=>"12.1","p1"=>"13.7","p2"=>"15.7","p3"=>"18"],
            ["id"=>"90","jenis_kelamin"=>"P","umur"=>"28","m3"=>"8.6","m2"=>"9.7","m1"=>"10.9","median"=>"12.3","p1"=>"14","p2"=>"16","p3"=>"18.3"],
            ["id"=>"91","jenis_kelamin"=>"P","umur"=>"29","m3"=>"8.8","m2"=>"9.8","m1"=>"11.1","median"=>"12.5","p1"=>"14.2","p2"=>"16.2","p3"=>"18.7"],
            ["id"=>"92","jenis_kelamin"=>"P","umur"=>"30","m3"=>"8.9","m2"=>"10","m1"=>"11.2","median"=>"12.7","p1"=>"14.4","p2"=>"16.5","p3"=>"19"],
            ["id"=>"93","jenis_kelamin"=>"P","umur"=>"31","m3"=>"9","m2"=>"10.1","m1"=>"11.4","median"=>"12.9","p1"=>"14.7","p2"=>"16.8","p3"=>"19.3"],
            ["id"=>"94","jenis_kelamin"=>"P","umur"=>"32","m3"=>"9.1","m2"=>"10.3","m1"=>"11.6","median"=>"13.1","p1"=>"14.9","p2"=>"17.1","p3"=>"19.6"],
            ["id"=>"95","jenis_kelamin"=>"P","umur"=>"33","m3"=>"9.3","m2"=>"10.4","m1"=>"11.7","median"=>"13.3","p1"=>"15.1","p2"=>"17.3","p3"=>"20"],
            ["id"=>"96","jenis_kelamin"=>"P","umur"=>"34","m3"=>"9.4","m2"=>"10.5","m1"=>"11.9","median"=>"13.5","p1"=>"15.4","p2"=>"17.6","p3"=>"20.3"],
            ["id"=>"97","jenis_kelamin"=>"P","umur"=>"35","m3"=>"9.5","m2"=>"10.7","m1"=>"12","median"=>"13.7","p1"=>"15.6","p2"=>"17.9","p3"=>"20.6"],
            ["id"=>"98","jenis_kelamin"=>"P","umur"=>"36","m3"=>"9.6","m2"=>"10.8","m1"=>"12.2","median"=>"13.9","p1"=>"15.8","p2"=>"18.1","p3"=>"20.9"],
            ["id"=>"99","jenis_kelamin"=>"P","umur"=>"37","m3"=>"9.7","m2"=>"10.9","m1"=>"12.4","median"=>"14","p1"=>"16","p2"=>"18.4","p3"=>"21.3"],
            ["id"=>"100","jenis_kelamin"=>"P","umur"=>"38","m3"=>"9.8","m2"=>"11.1","m1"=>"12.5","median"=>"14.2","p1"=>"16.3","p2"=>"18.7","p3"=>"21.6"],
            ["id"=>"101","jenis_kelamin"=>"P","umur"=>"39","m3"=>"9.9","m2"=>"11.2","m1"=>"12.7","median"=>"14.4","p1"=>"16.5","p2"=>"19","p3"=>"22"],
            ["id"=>"102","jenis_kelamin"=>"P","umur"=>"40","m3"=>"10.1","m2"=>"11.3","m1"=>"12.8","median"=>"14.6","p1"=>"16.7","p2"=>"19.2","p3"=>"22.3"],
            ["id"=>"103","jenis_kelamin"=>"P","umur"=>"41","m3"=>"10.2","m2"=>"11.5","m1"=>"13","median"=>"14.8","p1"=>"16.9","p2"=>"19.5","p3"=>"22.7"],
            ["id"=>"104","jenis_kelamin"=>"P","umur"=>"42","m3"=>"10.3","m2"=>"11.6","m1"=>"13.1","median"=>"15","p1"=>"17.2","p2"=>"19.8","p3"=>"23"],
            ["id"=>"105","jenis_kelamin"=>"P","umur"=>"43","m3"=>"10.4","m2"=>"11.7","m1"=>"13.3","median"=>"15.2","p1"=>"17.4","p2"=>"20.1","p3"=>"23.4"],
            ["id"=>"106","jenis_kelamin"=>"P","umur"=>"44","m3"=>"10.5","m2"=>"11.8","m1"=>"13.4","median"=>"15.3","p1"=>"17.6","p2"=>"20.4","p3"=>"23.7"],
            ["id"=>"107","jenis_kelamin"=>"P","umur"=>"45","m3"=>"10.6","m2"=>"12","m1"=>"13.6","median"=>"15.5","p1"=>"17.8","p2"=>"20.7","p3"=>"24.1"],
            ["id"=>"108","jenis_kelamin"=>"P","umur"=>"46","m3"=>"10.7","m2"=>"12.1","m1"=>"13.7","median"=>"15.7","p1"=>"18.1","p2"=>"20.9","p3"=>"24.5"],
            ["id"=>"109","jenis_kelamin"=>"P","umur"=>"47","m3"=>"10.8","m2"=>"12.2","m1"=>"13.9","median"=>"15.9","p1"=>"18.3","p2"=>"21.2","p3"=>"24.8"],
            ["id"=>"110","jenis_kelamin"=>"P","umur"=>"48","m3"=>"10.9","m2"=>"12.3","m1"=>"14","median"=>"16.1","p1"=>"18.5","p2"=>"21.5","p3"=>"25.2"],
            ["id"=>"111","jenis_kelamin"=>"P","umur"=>"49","m3"=>"11","m2"=>"12.4","m1"=>"14.2","median"=>"16.3","p1"=>"18.8","p2"=>"21.8","p3"=>"25.5"],
            ["id"=>"112","jenis_kelamin"=>"P","umur"=>"50","m3"=>"11.1","m2"=>"12.6","m1"=>"14.3","median"=>"16.4","p1"=>"19","p2"=>"22.1","p3"=>"25.9"],
            ["id"=>"113","jenis_kelamin"=>"P","umur"=>"51","m3"=>"11.2","m2"=>"12.7","m1"=>"14.5","median"=>"16.6","p1"=>"19.2","p2"=>"22.4","p3"=>"26.3"],
            ["id"=>"114","jenis_kelamin"=>"P","umur"=>"52","m3"=>"11.3","m2"=>"12.8","m1"=>"14.6","median"=>"16.8","p1"=>"19.4","p2"=>"22.6","p3"=>"26.6"],
            ["id"=>"115","jenis_kelamin"=>"P","umur"=>"53","m3"=>"11.4","m2"=>"12.9","m1"=>"14.8","median"=>"17","p1"=>"19.7","p2"=>"22.9","p3"=>"27"],
            ["id"=>"116","jenis_kelamin"=>"P","umur"=>"54","m3"=>"11.5","m2"=>"13","m1"=>"14.9","median"=>"17.2","p1"=>"19.9","p2"=>"23.2","p3"=>"27.4"],
            ["id"=>"117","jenis_kelamin"=>"P","umur"=>"55","m3"=>"11.6","m2"=>"13.2","m1"=>"15.1","median"=>"17.3","p1"=>"20.1","p2"=>"23.5","p3"=>"27.7"],
            ["id"=>"118","jenis_kelamin"=>"P","umur"=>"56","m3"=>"11.7","m2"=>"13.3","m1"=>"15.2","median"=>"17.5","p1"=>"20.3","p2"=>"23.8","p3"=>"28.1"],
            ["id"=>"119","jenis_kelamin"=>"P","umur"=>"57","m3"=>"11.8","m2"=>"13.4","m1"=>"15.3","median"=>"17.7","p1"=>"20.6","p2"=>"24.1","p3"=>"28.5"],
            ["id"=>"120","jenis_kelamin"=>"P","umur"=>"58","m3"=>"11.9","m2"=>"13.5","m1"=>"15.5","median"=>"17.9","p1"=>"20.8","p2"=>"24.4","p3"=>"28.8"],
            ["id"=>"121","jenis_kelamin"=>"P","umur"=>"59","m3"=>"12","m2"=>"13.6","m1"=>"15.6","median"=>"18","p1"=>"21","p2"=>"24.6","p3"=>"29.2"],
            ["id"=>"122","jenis_kelamin"=>"P","umur"=>"60","m3"=>"12.1","m2"=>"13.7","m1"=>"15.8","median"=>"18.2","p1"=>"21.2","p2"=>"24.9","p3"=>"29.5"]
        ];

        foreach ($standarBbsData as $data) {
            StandarBb::create([
                'jenis_kelamin' => $data['jenis_kelamin'],
                'umur' => $data['umur'],
                'm3' => $data['m3'],
                'm2' => $data['m2'],
                'm1' => $data['m1'],
                'median' => $data['median'],
                'p1' => $data['p1'],
                'p2' => $data['p2'],
                'p3' => $data['p3'],
            ]);
        }

        // Create Perkembangan data - Complete dataset
        $perkembanganData = [
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"#Bayi Terlentangkan:","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"1. Pada waktu bayi terlentang, apakah masing-masing lengan dan tungkai \r\nbergerak dengan mudah? Jawaban TIDAK bila salah satu atau kedua tungkai \r\natau lengan bayi bergerak tak terarah\/tak terkendali","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"2. Pada waktu bayi terlentang apakah ia melihat dan menatap wajah anda?","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"3. Apakah bayi dapat mengeluarkan suara-suara lain (ngoceh) selain menangis?","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"4. Pada waktu anda mengajak bayi berbicara dan tersenyum, apakah ia \r\ntersenyum kembali kepada anda","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"5. Apakah bayi suka tertawa keras walau tidak digelitik atau diraba-raba?","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"6. Ambil wool merah, letakkan di atas wajah di \r\ndepan mata, gerakkan wool dari samping kiri ke \r\nkanan kepala. Apakah ia dapat mengikuti gerakan \r\nanda dengan menggerakkan kepalanya dari \r\nkanan\/kiri ke tengah?","gambar"=>"3_6.png"],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"7. Ambil wool merah, letakkan di atas wajah di \r\ndepan mata, gerakkan wool dari samping kiri ke \r\nkanan kepala. Apakah ia dapat mengikuti gerakan \r\nanda dengan menggerakkan kepalanya dari satu \r\nsisi hampir sampai pada sisi yang lain?","gambar"=>"3_7.png"],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"#Bayi Telungkupkan:","gambar"=>""],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"8. Pada waktu bayi telungkup di alas yang datar, \r\napakah ia dapat mengangkat kepalanya seperti \r\npada gambar ini?","gambar"=>"3_8.png"],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"9. Pada waktu bayi telungkup di alas yang datar, \r\napakah ia dapat mengangkat kepalanya sehingga \r\nmembentuk sudut 45 derajat seperti pada gambar?","gambar"=>"3_9.png"],
            ["bulan"=>"3","usia_bayi_id"=>"1","text"=>"10. Pada waktu bayi telungkup di alas yang datar, \r\napakah ia dapat mengangkat kepalanya dengan \r\ntegak seperti pada gambar?","gambar"=>"3_10.png"],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"#Bayi Terlentangkan:","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"1. Ambil wool merah, letakkan di atas wajah di depan mata, \r\ngerakkan wool dari samping kiri ke kanan kepala. Apakah ia \r\ndapat mengikuti gerakan anda dengan menggerakkan kepala \r\nsepenuhnya dari satu ke sisi yang lain?","gambar"=>"6_1.png"],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"2. Pada posisi bayi terlentang, pegang kedua tangannya lalu tarik \r\nperlahan-lahan ke posisi duduk. Dapatkah bayi mempertahankan \r\nlehernya secara kaku seperti gambar? Jawab TIDAK bila kepala \r\nbayi jatuh kembali seperti gambar.","gambar"=>"6_2.png"],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"#Bayi Telungkupkan:","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"3. Ketika bayi telungkup di alas datar, apakah ia dapat mengangkat \r\ndada dengan kedua lengannya sebagai penyangga seperti pada \r\ngambar?","gambar"=>"6_3.png"],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"#Bayi dipangku ibunya \/ pengasuh di tepi meja periksa:","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"4. Dapatkah bayi mempertahankan posisi kepala dalam \r\nkeadaan tegak dan stabil? Jawab TIDAK bila kepala bayi \r\ncenderung jatuh ke kanan\/kiri atau ke dadanya","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"5. Sentuhkan pensil di punggung tangan atau ujung jari bayi (jangan meletakkan di atas \r\ntelapak tangan bayi). Apakah bayi dapat menggenggam pensil itu selama beberapa \r\ndetik?","gambar"=>"6_5.png"],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"6. Dapatkah bayi mengarahkan matanya pada benda kecil sebesar kacang, kismis atau \r\nuang logam? Jawab TIDAK jika ia tidak dapat mengarahkan matanya.","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"7. Dapatkah bayi meraih mainan yang diletakkan agak jauh namun masih berada dalam \r\njangkauan tangannya?","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"#Tanya Ibu \/ Pengasuh :","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"8.Pernahkah bayi mengeluarkan suara gembira bernada tinggi atau memekik tetapi bukan \r\nmenangis?","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"9. Pernahkah bayi berbalik paling sedikit dua kali, dari terlentang ke telungkup atau \r\nsebaliknya?","gambar"=>""],
            ["bulan"=>"6","usia_bayi_id"=>"2","text"=>"10. Pernahkah anda melihat bayi tersenyum ketika melihat mainan yang lucu, gambar atau \r\nbinatang peliharaan pada saat ia bermain sendiri?","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"#Bayi Terlentangkan:","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"1. Pada posisi bayi telentang, pegang kedua \r\ntangannya lalu tarik perlahan-lahan ke posisi \r\nduduk. Dapatkah bayi mempertahankan \r\nlehernya secara kaku seperti gambar di \r\nsebelah kiri ?\r\nJawab TIDAK bila kepala bayi jatuh kembali seperti gambar sebelah kanan.","gambar"=>"9_1.png"],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"#Bayi dipangku ibunya\/pengasuh di tepi meja periksa","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"2. Tarik perhatian bayi dengan memperlihatkan wool merah, kemudian jatuh \r\nkan ke lantai. Apakah bayi mencoba mencarinya? Misalnya mencari di \r\nbawah meja atau di belakang kursi?","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"3. Taruh 2 kubus di atas meja, buat agar bayi dapat memungut masing-masing \r\nkubus dengan masing-masing tangan dan memegang satu kubus pada \r\nmasing-masing tangannya","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"4. Taruh kismis di atas meja. Dapatkah bayi memungut \r\ndengan tangannya benda-benda kecil seperti \r\nkismis, kacang-kacangan, potongan biskuit, \r\ndengan gerakan miring atau menggerapai \r\nseperti gambar ?","gambar"=>"9_4.png"],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"5. Letakkan suatu mainan yang dinginkannya di luar jangkauan bayi, apakah ia \r\nmencoba mendapatkannya dengan mengulurkan lengan atau badannya?","gambar"=>"9_5.png"],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"#Tanya Ibu\/Pengasuh","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"6. Apakah pernah melihat bayi memindahkan mainan atau kue kering dari satu \r\ntangan ke tangan yang lain? Benda-benda panjang seperti sendok atau \r\nkerincingan bertangkai tidak ikut dinilai.","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"7. Apakah bayi dapat makan kue kering sendiri?","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"8. Pada waktu bayi bermain sendiri dan ibu diam-diam datang berdiri di \r\nbelakangnya, apakah ia menengok ke belakang seperti mendengar kedatangan \r\nanda?\r\nSuara keras tidak ikut dihitung. Jawab YA hanya jika anda melihat reaksinya \r\nterhadap suara yang perlahan atau bisikan.","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"#Bayi dipangku pemeriksa","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"9. Jika anda mengangkat bayi melalui ketiaknya ke posisi berdiri, dapatkah ia \r\nmenyangga sebagian berat badan dengan kedua kakinya? Jawab YA bila ia \r\nmencoba berdiri dan sebagian berat badan tertumpu pada kedua kakinya.","gambar"=>""],
            ["bulan"=>"9","usia_bayi_id"=>"3","text"=>"10. Tanpa disangga oleh bantal, kursi atau dinding, dapatkah \r\nbayi duduk sendiri selama 60 detik?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"#Bayi dipangku ibunya\/pengasuh di tepi meja periksa","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"1. Letakkan pensil di telapak tangan bayi. Coba ambil pensil tersebut \r\ndengan perlahan-lahan. Sulitkah anda mendapatkan pensil itu \r\nkembali?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"2. Taruh kismis di atas meja. Dapatkah bayi memungut dengan tangannya \r\nbenda-benda kecil seperti kismis, kacang-kacangan, potongan biskuit, \r\ndengan gerakan miring atau menggerapai seperti gambar ?","gambar"=>"12_2.png"],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"3. Tanpa bantuan,apakah anak dapat mempertemukan dua kubus kecil \r\nyang ia pegang?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"4. Sebut 2-3 kata yang dapat ditiru oleh anak (tidak perlu kata-kata \r\nyang lengkap). Apakah ia mencoba meniru menyebutkan kata-kata \r\ntadi ?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"#Tanya Ibu\/Pengasuh","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"5. Jika anda bersembunyi di belakang sesuatu\/di pojok, kemudian \r\nmuncul dan menghilang secara berulang-ulang di hadapan anak, \r\napakah ia mencari anda atau mengharapkan anda muncul kembali?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"6. Apakah anak dapat mengangkat badannya ke posisi berdiri tanpa \r\nbantuan anda?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"7. Apakah anak dapat membedakan anda dengan orang yang belum ia \r\nkenal? Ia akan menunjukkan sikap malu-malu atau ragu-ragu pada \r\nsaat permulaan bertemu dengan orang yang belum dikenalnya.","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"8. Apakah anak dapat duduk sendiri tanpa bantuan?","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"9. Apakah anak dapat mengatakan 2 suku kata yang sama, misalnya: \r\n\"ma-ma\", \"da-da\" atau \"pa-pa\". Jawab YA bila ia mengeluarkan \r\nsalah satu suara tadi.","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"#Coba berdirikan anak:","gambar"=>""],
            ["bulan"=>"12","usia_bayi_id"=>"4","text"=>"10. Apakah anak dapat berdiri selama 30 detik atau lebih dengan berpegangan \r\npada kursi\/meja?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"#Anak dipangku ibunya\/pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"1. Beri 2 kubus, tanpa bantuan, apakah anak dapat mempertemukan dua \r\nkubus kecil yang ia pegang?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"2. Apakah anak anak dapat mengambil benda kecil seperti kacang, kismis, \r\natau potongan biskuit dengan menggunakan ibu jari dan jari telunjuk \r\nseperti pada gambar ?","gambar"=>"15_2.png"],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"#Tanya Ibu\/Pengasuh","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"3. Apakah anak dapat jalan sendiri atau jalan dengan berpegangan?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"4. Tanpa bantuan, apakah anak dapat bertepuk tangan atau melambai\u0002lambai?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"5. Jawab TIDAK bila ia membutuh kan bantuan\r\nApakah anak dapat mengatakan \"papa\" ketika ia memanggil\/melihat\r\nayahnya, atau mengatakan \"mama\" jika memanggil\/melihat ibunya?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"6. Jawab YA bila anak mengatakan salah satu diantaranya\r\nApakah anak dapat menunjukkan apa yang diinginkannya tanpa \r\nmenangis atau merengek? Jawab YA bila ia menunjuk, menarik atau \r\nmengeluarkan suara yang menyenangkan","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"#Coba berdirikan anak:","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"7.Apakah anak dapat berdiri sendiri tanpa berpegangan selama kira-kira \r\n5 detik?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"8. Apakah anak dapat berdiri sendiri tanpa berpegangan selama 30 detik\r\natau lebih?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"9. Taruh kubus di lantai, tanpa berpegangan atau menyentuh lantai, \r\napakah anak dapat membungkuk untuk memungut kubus di lantai dan \r\nkemudian berdiri kembali?","gambar"=>""],
            ["bulan"=>"15","usia_bayi_id"=>"5","text"=>"10. Apakah anak dapat berjalan di sepanjang ruangan tanpa jatuh \r\natauterhuyung-huyung?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"#Anak dipangku ibunya \/ Pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"1. Letakkan kismis diatas meja dekat anak, apakah anak dapat mengambil\r\ndengan ibu jari dan telunjuk?","gambar"=>"18_1.png"],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"2. Gelindingkan bola tenis ke arah anak, apakah dapat mengelindingkan \r\n\/melempar bola kembali kepada anak?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"#Tanya ibu","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"3. Apakah anak dapat bertepuk tangan atau melambaikan tangan tanpa \r\nbantuan?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"4. Apakah anak dapat mengatakan \"papa\" ketika melihat atau memanggil\r\nayahnya atau mengatakan \"mama\" ketika melihat atau memanggil \r\nibunya?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"5. Apakah anak dapat menunjukkan apa yang diingikan tanpa menangis \r\natau merengek?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"6. Apakah anak dapat minum dari cangkir\/gelas sendiri tanpa tumpah?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"#Coba berdirikan anak:","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"7. Apakah anak dapat berdiri kira-kira 5 detik tanpa pegangan?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"8. Apakah anak dapat berdiri kira kira lebih dari 30 detik tanpa pegangan?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"9. Letakkan kubus di lantai, minta anak memungut, apakah anak dapat \r\nmemungut dan berdiri kembali tanpa berpegangan?","gambar"=>""],
            ["bulan"=>"18","usia_bayi_id"=>"6","text"=>"10. Minta anak berjalan sepanjang ruangan, dapatkan ia berjalan tanpa \r\nterhunyung\/jatuh?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"#Anak dipangku ibunya \/ Pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"1. Letakkan kismis diatas meja dekat anak, apakah anak dapat mengambil\r\ndengan ibu jari dan telunjuk?","gambar"=>"21_1.png"],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"2. Gelindingkan bola tenis ke arah anak, apakah dapat mengelindingkan \r\n\/melempar bola kembali kepada anak?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"3. Beri kubus didepannya. Minta anak meletakkan 1 kubus diatas kubus \r\nlainnya (1 tingkat saja)","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"#Tanya ibu","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"4. Apakah anak dapat menunjukkan apa yang diinginkan tanpa menangis \r\natau merengek?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"5. Apakah anak dapat minum dari cangkir\/gelas sendiri tanpa tumpah?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"6. Apakah anak suka meniru bila ibu sedang melakukan pekerjaan rumah\r\ntangga (menyapu, mencuci, dll)","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"7. Apakah anak dapat mengucapkan minimal 3 kata yang mempunyai arti\r\n(selain kata mama dan papa)?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"8. Apakah anak pernah berjalan mundur minimal 5 langkah?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"#Coba berdirikan anak","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"9. Letakkan kubus di lantai, minta anak memungut, apakah anak dapat\r\nmemungut dan berdiri kembali tanpa berpegangan?","gambar"=>""],
            ["bulan"=>"21","usia_bayi_id"=>"7","text"=>"10. Minta anak berjalan sepanjang ruangan, dapatkan ia berjalan tanpa\r\nterhunyung\/jatuh?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"#Anak dipangku ibunya \/ Pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"1. Apakah anak dapat meletakkan satu kubus di atas kubus yang lain \r\ntanpa menjatuhkan kubus itu?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"2. Tanpa bimbingan, petunjuk, atau bantuan anda, dapatkah anak menunjuk\r\ndengan benar paling sedikit satu bagian badannya (rambut, mata, \r\nhidung, mulut, atau bagian badan yang lain)?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"Tanya ibu","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"3. Apakah anak suka meniru bila ibu sedang melakukan pekerjaan rumah\r\ntangga (menyapu, mencuci, dll)?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"4. Apakah anak dapat mengucapkan paling sedikit 3 kata yang mempunyai \r\narti selain \"papa\" dan \"mama\"?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"5. Apakah anak berjalan mundur 5 langkah atau lebih tanpa kehilangan \r\nkeseimbangan? (Anda mungkin dapat melihatnya ketika anak menarik \r\nmainannya)","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"6. Dapatkah anak melepas pakaiannya seperti : Baju, Rok, atau celananya ?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"7. Dapatkah anak berjalan naik tangga sendiri? Jawab YA jika ia naik tangga \r\ndengan posisi tegak atau berpegangan pada dinding atau pegangan \r\ntangga. Jawab TIDAK jika ia naik tangga dengan merangkak atau anda \r\ntidak mebolehkan anak naik tangga atau anak harus berpegangan pada \r\nseseorang.","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"8. Dapatkah anak makan nasi sendiri tanpa banyak tumpah?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"9. Dapatkah anak membantu memungt mainannya sendiri atau \r\nmembantu mengangkat piring jika diminta?","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"#Berdirikan anak","gambar"=>""],
            ["bulan"=>"24","usia_bayi_id"=>"8","text"=>"10. Letakkan bola tenis di depan kakinya. Apakah dia dapat menendangnya,\r\ntanpa berpegangan pada apapun?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"#Anak dipangku ibunya \/ Pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"1. Tanpa bimbingan, petunjuk atau bantuan anda, dapatkah anak menunjuk dengan  benar  paling  sedikit  satu  bagian  badannya  (rambut,  mata, hidung, mulut, atau bagian badan yang lain)?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"2. Beri kubus di depannya. Dapatkah anak meletakkan 4 buah kubus satupersatu di atas kubus yang lain tanpa menjatuhkan kubus itu?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"3. Apakah anak dapat menyebut 2 diantara gambar-gambar ini tanpa bantuan?  (menyebut dengan suara binatang tidak ikut dinilai)","gambar"=>"30_3.png"],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"4. Bila    diberi    pensil,    apakah    anak    mencoret-coret    kertas    tanpa bantuan\/petunjuk?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"#Tanya ibu","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"5. Dapatkah anak melepas pakaiannya seperti: baju, rok, atau celananya?(topi dan kaos kaki tidak ikut dinilai).","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"6. Dapatkah anak berjalan naik tangga sendiri?Jawab  YA.  Jika  ia  naik  tangga  dengan  posisi  tegak  atau  berpegangan pada  dinding  atau  pegangan  tangga  Jawab  TIDAK.  Jika  ia  naik  tangga dengan merangkak atau anda tidak membolehkan anak naik tangga atau anak harus berpegangan pada seseorang.","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"7. Dapatkah anak makan nasi sendiri tanpa banyak tumpah?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"8. Dapatkah  anak  membantu  memungut  mainannya  sendiri  atau  mem-bantu mengangkat piring jika diminta?","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"9. Dapatkah anak menggunakan 2 kata pada saat berbicara seperti \"mintaminum\", \"mau tidur\"? \"Terimakasih\" dan \"Dadag\" tidak ikut dinilai.","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"#Berdirikan anak","gambar"=>""],
            ["bulan"=>"30","usia_bayi_id"=>"9","text"=>"10. Letakkan  bola  tenis  didpn  kakinya.  Dapatkah  anak  menendang  bola kecil  (sebesar  bola  tenis)  ke  depan  tanpa  berpegangan  pada  apapun? Mendorong tidak ikut dinilai","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"#Anak dipangku ibunya \/ Pengasuh ditepi meja periksa","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"1. Beri kubus di depannya.\r\nDapatkah anak meletakkan 4 buah kubus satu persatu di atas kubus \r\nyang lain tanpa menjatuhkan kubus itu?","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"2. Apakah anak dapat menyebut 2 diantara gambar- gambar ini tanpa \r\nbantuan? (Menyebut dengan suara binatang tidak ikut dinilai)","gambar"=>"36_2.png"],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"3. Bila diberi pensil, apakah anak mencoret-coret kertas tanpa bantuan\/petuniuk?","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"4. Buat garis lurus ke bawah sepanjang sekurang- kurangnya 2.5 cm. Suruh \r\nanak menggambar garis lain di samping garis ini.\r\nJawab YA bila ia menggambar garis seperti gambar 1\r\nJawab TIDAK bila ia menggambar garis seperti gambar 2","gambar"=>"36_4.png"],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"#Tanya ibu","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"5. Dapatkah anak menggunakan 2 kata berangkai pada saat berbicara seperti\r\n\"minta minum\", \"mau tidur''?\r\n\"Terimakasih\" dan \"Dadag\" tidak ikut dinilai","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"6. Dapatkah anak mengenakan sepatunya sendiri?","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"7. Dapatkah anak mengayuh sepeda roda tiga sejauh sedikitnya 3 meter?","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"#Berdirikan anak","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"8. lkuti perintah ini dengan seksama. Jangan memberi isyarat dengan \r\ntelunjuk atau mata pada saat memberikan perintah berikut ini:\r\n\"Letakkan kertas ini di lantai\".\r\n\"Letakkan kertas ini di kursi\".\r\n\"Berikan kertas ini kepada ibu\"","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"9. Dapatkah anak melaksanakan ketiga perintah tadi?\r\nLetakkan selembar kertas seukuran buku ini di lantai. Apakah anak \r\ndapat melompati bagian lebar kertas dengan mengangkat kedua \r\nkakinya secara bersamaan tanpa didahului lari?","gambar"=>""],
            ["bulan"=>"36","usia_bayi_id"=>"10","text"=>"10. Beri bola tenis. Minta anak melemparkan kearah dada anda. Dapatkah \r\nanak melempar bola lurus ke arah perut atau dada anda dari jarak 1,5 \r\nmeter?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"#Anak dipangku Ibunya\/duduk sendiri di tepi meja periksa","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"1. Beri kubus di depannya. Dapatkah anak meletakkan 8 buah kubus satu \r\npersatu di atas yang lain tanpa menjatuhkan kubus tersebut?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"2. Beri pensil dan kertas. Buatlah lingkaran di atas kertas tersebut.Minta anak \r\nmenirunya. Dapatkah anak menggambar lingkaran?","gambar"=>"42_2.png"],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"#Tanya Ibu\/Pengasuh:","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"3. Dapatkah anak mengenakan sepatunya sendiri?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"4. Dapatkah anak mengayuh sepeda roda tiga sejauh sedikitnya 3 meter?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"5. Apakah anak dapat mencuci tangannya sendiri dengan baik setelah makan?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"6. Apakah anak dapat mengikuti peraturan permainan bila bermain dengan \r\nteman-temannya? (misal: ular tangga, petak umpet, dll)","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"7. Dapatkah anak mengenakan celana panjang, kemeja, baju atau kaos kaki \r\ntanpa di bantu? (Tidak termasuk memasang kancing, gesper atau ikat \r\npinggang)","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"#Minta anak untuk berdiri","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"8. Suruh anak berdiri satu kaki tanpa berpegangan. Jika perlu tunjukkan\r\ncaranya dan beri anak anda kesempatan melakukannya 3 kali. Dapatkah ia\r\nmempertahankan keseimbangan dalam waktu 2 detik atau lebih?","gambar"=>""],
            ["bulan"=>"42","usia_bayi_id"=>"11","text"=>"9. Letakkan selembar kertas seukuran buku ini di lantai. Apakah anak dapat \r\nmelompati panjang kertas ini dengan mengangkat kedua kakinya secara \r\nbersamaan tanpa didahului lari?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"1. Dapatkah anak mengayuh sepeda roda tiga sejauh sedikitnya 3 meter?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"2. Setelah makan, apakah anak mencuci dan mengeringkan tangannya dengan baik sehingga anda tidak perlu mengulanginya?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"3. Suruh anak berdiri satu kaki tanpa berpegangan. Jika perlu tunjukkan caranya dan beri anak anda kesempatan melakukannya 3kali. Dapatkah ia mempertahankan keseimbangan dalam waktu 2 detik atau lebih?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"4. Letakkan selembar kertas seukuran buku ini di lantai. Apakah anak dapat melompati panjang kertas ini dengan mengangkat kedua kakinya secara bersamaan tanpa didahului lari?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"5. Jangan membantu anak dan jangan menyebut lingkaran. Suruh anak menggambar seperti contoh ini di kertas kosong yang tersedia. Dapatkah anak menggambar lingkaran?","gambar"=>"48_5.png"],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"6. Dapatkah anak meletakkan 8 buah kubus satu persatu di atas yang lain tanpa menjatuhkan kubus tersebut? Kubus yang digunakan ukuran 2.5-5 cm.","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"7. Apakah anak dapat bermain petak umpet, ular naga atau permainan lain dimana ia ikut bermain dan mengikuti aturan bermain?","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"8. Dapatkah anak mengenakan celana panjang, kemeja, baju atau kaos kaki tanpa di bantu? (Tidak termasuk memasang kancing, gesper atau ikat pinggang)","gambar"=>""],
            ["bulan"=>"48","usia_bayi_id"=>"12","text"=>"9. Dapatkah anak menyebutkan nama lengkapnya tanpa dibantu? Jawab TIDAK jika ia hanya menyebutkan sebagian namanya atau ucapannya sulit dimengerti.","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"1. Dapatkah anak meletakkan 8 buah kubus satu persatu di atas yang lain tanpa menjatuhkan kubus tersebut? Kubus yang digunakan ukuran 2.5-5 cm.","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"2. Apakah anak dapat bermain petak umpet, ular naga atau permainan lain dimana ia ikut bermain dan mengikuti aturanbermain?","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"3. Dapatkah anak mengenakan celana panjang, kemeja, baju atau kaos kaki tanpa di bantu? (Tidak termasuk memasang kancing, gesper atau ikat pinggang)","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"4. Dapatkah anak menyebutkan nama lengkapnya tanpa dibantu? Jawab TIDAK jika ia hanya menyebut sebagian namanya atau ucapannya sulit dimengerti.","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"5. Isi titik-titik di bawah ini dengan jawaban anak. Jangan membantu kecuali mengulangi pertanyaan. \"Apa yang kamu lakukan jika kamu kedinginan?\" \"Apa yang kamu lakukan jika kamu lapar?\" \"Apa yang kamu lakukan jika kamu lelah?\" Jawab YA biia anak merjawab ke 3 pertanyaan tadi dengan benar, bukan dengan gerakan atau isyarat. Jika kedinginan, jawaban yang benar adalah \"menggigil\" ,\"pakai mantel\" atau \"masuk kedalam rumah\". Jika lapar, jawaban yang benar adalah \"makan\" Jika lelah, jawaban yang benar adalah \"mengantuk\", \"tidur\", \"berbaring\/tidur-tiduran\", \"istirahat\" atau \"diam sejenak\"","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"6. Apakah anak dapat mengancingkan bajunya atau pakaian boneka?","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"7. Suruh anak berdiri satu kaki tanpa berpegangan. Jika perlu tunjukkan caranya dan beri anak ands kesempatan melakukannya 3 kali. Dapatkah ia mempertahankan keseimbangan dalam waktu 6 detik atau lebih?","gambar"=>""],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"8. Jangan mengoreksi\/membantu anak. Jangan menyebut kata \"lebih panjang\". Perlihatkan gambar kedua garis ini pada anak. Tanyakan: \"Mana garis yang lebih panjang?\" Minta anak menunjuk garis yang lebih panjang. \r\nSetelah anak menunjuk, putar lembar ini dan ulangi pertanyaan tersebut. Setelah anak menunjuk, putar lembar ini lagi dan ulangi pertanyaan tadi. Apakah anak dapat menunjuk garis yang lebih panjang sebanyak 3 kali dengan benar?","gambar"=>"54_8.png"],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"9. Jangan membantu anak dan jangan memberitahu nama gambar ini, suruh anak menggambar seperti contoh ini di kertas kosong yang tersedia. Berikan 3 kali kesempatan. Apakah anak dapat menggambar seperti contoh ini?","gambar"=>"54_9.png"],
            ["bulan"=>"54","usia_bayi_id"=>"13","text"=>"10. Ikuti perintah ini dengan seksama. Jangan memberi isyarat dengan telunjuk atau mats pads saat memberikan perintah berikut ini: \"Letakkan kertas ini di atas lantai\". \"Letakkan kertas ini di bawah kursi\". \"Letakkan kertas ini di depan kamu\" \"Letakkan kertas ini di belakang kamu\" Jawab YA hanya jika anak mengerti arti \"di atas\", \"di bawah\", \"di depan\" dan \"di belakang\"","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"1. Isi titik-titik di bawah ini dengan jawaban anak. Jangan membantu kecuali mengulangi pertanyaan.\"Apa yang kamu lakukan jika kamu kedinginan?\"\"Apa yang kamu lakukan jika kamu lapar?\"\"Apa yang kamu lakukan jika kamu lelah?\"Jawab YA biia anak merjawab ke 3 pertanyaan tadi dengan benar, bukan dengan gerakan atau isyarat.Jika kedinginan, jawaban yang benar adalah \"menggigil\" ,\"pakai mantel\" atau \"masuk kedalam rumah\".Jika lapar, jawaban yang benar adalah \"makan\"Jika lelah, jawaban yang benar adalah \"mengantuk\", \"tidur\", \"berbaring\/tidur-tiduran\", \"istirahat\" atau \"diam sejenak","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"2. Apakah anak dapat mengancingkan bajunya atau pakaian boneka?","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"3. Suruh anak berdiri satu kaki tanpa berpegangan. Jika perlu tunjukkan caranya dan beri anak ands kesempatan melakukannya 3 kali. Dapatkah ia mempertahankan keseimbangan dalam waktu 6 detik atau lebih?","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"4. Jangan mengoreksi\/membantu anak. Jangan menyebut kata \"lebih panjang\".Perlihatkan gambar kedua garis ini pada anak.Tanyakan: \"Mana garis yang lebih panjang?\"Minta anak menunjuk garis yang lebih panjang.Setelah anak menunjuk, putar lembar ini dan ulangi pertanyaan tersebut.\r\n20Setelah anak menunjuk, putar lembar ini lagi dan ulangi pertanyaan tadi.Apakah anak dapat menunjuk garis yang lebih panjang sebanyak 3 kali dengan benar?","gambar"=>"60_4.png"],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"5. Jangan membantu anak dan jangan memberitahu nama gambar ini, suruh anak menggambar seperti contoh ini di kertas kosong yang tersedia. Berikan 3 kali kesempatan. Apakah anak dapat menggambar seperti contoh ini?","gambar"=>"60_5.png"],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"6. Ikuti perintah ini dengan seksama. Jangan memberi isyarat dengan telunjuk atau mats pads saat memberikan perintah berikut ini: \"Letakkan kertas ini di atas lantai\".\"Letakkan kertas ini di bawah kursi\".\"Letakkan kertas ini di depan kamu\"\"Letakkan kertas ini di belakang kamu\"Jawab YA hanya jika anak mengerti arti \"di atas\", \"di bawah\", \"di depan\" dan \"di belakang\"","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"7. Apakah anak bereaksi dengan tenang dan tidak rewel (tanpa menangis atau menggelayut pada anda) pada saat anda meninqgalkannya?","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"8. Jangan menunjuk, membantu atau membetulkan, katakan pada anak : \"Tunjukkan segi empat merah\"\"Tunjukkan segi empat kuning\"\"Tunjukkansegi empat biru\"\"Tunjukkan segi empat hijau\"Dapatkah anak menunjuk keempat warna itu dengan benar?","gambar"=>"60_8.png"],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"9. Suruh anak melompat dengan satu kaki beberapa kali tanpa berpegangan (lompatan dengan dua kaki tidak ikut dinilai). Apakah ia dapat melompat 2-3 kali dengan satu kaki?","gambar"=>""],
            ["bulan"=>"60","usia_bayi_id"=>"14","text"=>"10. Dapatkah anak sepenuhnya berpakaian sendiri tanpa bantuan?","gambar"=>""]
        ];

        // Insert all Perkembangan data
        foreach ($perkembanganData as $data) {
            Perkembangan::create([
                'bulan' => $data['bulan'],
                'usia_bayi_id' => $data['usia_bayi_id'],
                'text' => $data['text'],
                'gambar' => $data['gambar'] ?: null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->call([
            UsiaBayiSeeder::class,
            PerkembanganSeeder::class,
            MateriSeeder::class,
        ]);
    }
}
